### ISSUE TITLE
Cannot change content name from the redirects tab

### ISSUE THREAD

**Issue by Luksor** [dawoe/umbraco-redirectsviewer#12]
Hi.

I've just found a little annoying bug:

If a doctype does not have any fields, you are not able to easily change the name from the first screen. To change it you need to switch to the Info tab everytime.

![image](https://user-images.githubusercontent.com/5837521/66939507-15bdae80-f03b-11e9-99a1-68b5a31f009b.png)

Is there a way of unlocking the name field or maybe moving the Redirects tab to appear after Info?

Thanks,
Lukasz

**Comment by dawoe** [comment]
Hi @Luksor 

The info content is always put last I think by Umbraco core.

What you could try is go in to the package manifest file for this content app and set the weight to something really high... for example 99999

Maybe it will be forced as last app

**Comment by ismailmayat** [comment]
cheers dave that worked

**Comment by Luksor** [comment]
Thank you @dawoe
