### ISSUE TITLE
Redirects Viewer doesn't play nice with multilingual setup

### ISSUE THREAD

**Issue by creativesuspects** [dawoe/umbraco-redirectsviewer#14]
When manually adding a redirect on a multilingual website to a page in the default language it works great. However, when manually adding a redirect to a page in a non-default language the source URL is generated based on the default language. So it's impossible to manually add redirects for non-default languages.

![screencast](https://i.imgur.com/TE2IhkR.gif)

Also, the list of existing redirects is not filtered based on the active culture. So when you're looking at the redirects for an en-US page it also shows the redirects for the (in this case default) nl-NL variant. I've tested this on Umbraco 8.2.0 using Redirects Viewer 2.0.0 (nuget).

**Comment by morin0094** [comment]
Ohh, that explains why my redirect dosen't work.

**Comment by morin0094** [comment]
Is it any update scheduled with this fix? I mean, it's a game changer.

**Comment by creativesuspects** [comment]
@morin0094 If you want you can use [this hotfix](https://www.dropbox.com/s/pxdmjf32jgu673h/Our.Umbraco.RedirectsViewer-hotfix.zip?dl=0) until the changes are merged into a new release.

**Comment by dawoe** [comment]
I have merged this one in. It's available in the latest beta at the moment and will release it later this week.

**Comment by creativesuspects** [comment]
Just installed version 2.1.0 via NuGet. Managing redirects on a multilingual website now works like a charm! 👍
