### ISSUE TITLE
Cannot create content nodes from doctypes with no properties.

### ISSUE THREAD

**Issue by Andrei-** [dawoe/umbraco-redirectsviewer#19]
Apparently if you have this package installed, if you have doctypes with no properties (like for folder nodes, or site-settings), you will not be able to create new items because the name textbox becomes disabled.
Did not test this thoroughly myself, but after asking Uaas support, they did and recommended me to uninstall the package.
![image](https://user-images.githubusercontent.com/6005180/79636324-19abc400-8177-11ea-80bb-00d7b11183cb.png)

**Comment by Andrei-** [comment]
[UPDATE] I did uninstall the package and now I can create content from doctypes without props. So this is a bug.

**Comment by dawoe** [comment]
Hi @Andrei- 

Which version of the package are you using. In the latest version the content app is not shown anymore when creating a item. 

Have you tried upgrading to v2.1.0

Dave

**Comment by Andrei-** [comment]
Hi @dawoe,

We were on version 2.0.0. 
Didn't try 2.1.0, as we moved to skybrud redirects package.
