### ISSUE TITLE
Creating redirects forces url to start with a /

### ISSUE THREAD

**Issue by sniffdk** [dawoe/umbraco-redirectsviewer#2]
Hi Dave 
Neat little package you got there :P
I'm having a minor annoyance with the ValidateUrl function though.
Seeing that the build-in function doesn't prefix registered url's with a "/", perhaps ValidateUrl shouldn't force it as well?
What do you think?

**Comment by dawoe** [comment]
I actually don't recall why I force it...will test without when I have time.

Dave

**Comment by sniffdk** [comment]
Great, let me know if I can do anything to help :)

**Comment by dawoe** [comment]
Hi @sniffdk 

If i don't prefix the url with a / it breaks getting redirects. It even breaks the standard dashboard

Dave

**Comment by sniffdk** [comment]
interesting 😅
