### ISSUE TITLE
Umbraco composers should be never internal

### ISSUE THREAD

**Issue by bielu** [dawoe/umbraco-redirectsviewer#22]
Hi @dawoe ,
Happy Christmas and sorry for writing on Christmas :C.
I found really critic issue with extensibility for your package :) 
In this file:
https://github.com/dawoe/umbraco-redirectsviewer/blob/develop/Source/Our.Umbraco.RedirectsViewer/Compositions/RedirectsViewerComposer.cs
You declare composer as internal, and that is thing which I was really time annoyed with umbraco as it is blocking possibilities of correct order of composers. And from my perspective when you doing that you are saying to other developers which would maybe use package as base to not do that as they are not able to resolve correctly order of composers.

**Comment by bielu** [comment]
HI @dawoe, 
I am not seeing any comment on that issue, do you want me to provide PR or more details?

**Comment by dawoe** [comment]
Hi @bielu 

I guess I missed this one due to the holidays. Please go ahead and create a PR.

Dave

**Comment by dawoe** [comment]
Hi @bielu 

I just released 2.2.0 which fixes this issue
