### ISSUE TITLE
Redirects Viewer does not seem to work in Umbraco 8.11.1

### ISSUE THREAD

**Issue by nielsodgaard** [dawoe/umbraco-redirectsviewer#27]
I recently upgraded an Umbraco website from 8.6.6 to 8.11.1. 
After the upgrade, new redirects added through the redirects viewer did not seem to work anymore.
The redirects added when renaming nodes still worked as usual.

Now I've just tried creating a new Umbraco 8.11.1 project with Redirects Viewer but all the redirects I add results in a page not found.

I see that some changes were made to Umbracos Redirect URL management recently and I guess it's those changes that is now causing Redirects Viewer to not work anymore.

**Comment by dawoe** [comment]
Hi @nielsodgaard 

Could be related to this Umbraco issue : https://github.com/umbraco/Umbraco-CMS/issues/9636

Can you tell me something more about your setup. Do you have culture variants etc...

That makes it easier for me to pinpoint the issue.

Also an example of redirect that you are trying to add could come in handy.

Dave

**Comment by dawoe** [comment]
By the way...I see this issue as well... even old redirects that are created by renaming a page don't work for me anymore on 8.11.1

**Comment by dawoe** [comment]
And mean redirects created by renaming prior to 8.11 upgrade

**Comment by dawoe** [comment]
Hi @nielsodgaard 

The issue with my package is fixed in the latest version that I just released.

If you have redirects that are not working you should update the umbracoRedirectUrl table. All records where the culture is `null ` should be changed to a empty string.

Dave

**Comment by nielsodgaard** [comment]
Hi @dawoe,

Wow that was fast. I'll upgrade asap.

Thank you very much.
