### ISSUE TITLE
Can this still run Umbraco 7?

### ISSUE THREAD

**Issue by bakgaard** [dawoe/umbraco-redirectsviewer#28]
According to the [.nuspec](https://github.com/dawoe/umbraco-redirectsviewer/blob/develop/Packaging/package.nuspec#L19) file, this must version 8 and not 7.15 - Can we do something about this?

And will it work for version 4.7.1?

**Comment by dawoe** [comment]
Hi @bakgaard ,

You need https://www.nuget.org/packages/Our.Umbraco.RedirectsViewer/1.3.0 for Umbraco 7

This will not work on Umbraco v 4.7.1

Dave
