### ISSUE TITLE
Dates aren't formatted in the view

### ISSUE THREAD

**Issue by kipusoep** [dawoe/umbraco-redirectsviewer#3]
The Created field isn't formatted as a readable date in the editor.
A way to fix this is to add this filter to the app:
```js
.filter('dateInMillis', function () {
    return function (dateString) {
        return Date.parse(dateString);
    };
});
```

And then use something like this in the view:
```html
<div class="umb-table-cell">
    {{item.createDateUtc | dateInMillis | date: 'short'}}
</div>
```

Note: I also removed the `<td />` tag around the date.

**Comment by dawoe** [comment]
Thx for reporting. Will try to get this in the next release

**Comment by dawoe** [comment]
This one is fixed in the latest beta release. Did not need to use the dateInMillis filter

This was enough :

```
<div class="umb-table-cell">
    {{item.createDateUtc | date: 'short'}}
</div>
```
