### ISSUE TITLE
Add redirect modal positioned outside viewport

### ISSUE THREAD

**Issue by kipusoep** [dawoe/umbraco-redirectsviewer#4]
They say a picture says more than a thousand words:

![image](https://user-images.githubusercontent.com/1866549/37582082-762c82fc-2b4b-11e8-8ffe-38a9c4df888b.png)

**Comment by dawoe** [comment]
Hmm.. have to figure out if it is my code causing it or if it is a issue with the umb-overlay directive.

https://github.com/dawoe/umbraco-redirectsviewer/blob/develop/Source/Our.Umbraco.RedirectsViewer/Web/App_Plugins/RedirectsViewer/views/editor.html#L59

It just position in the center.

Dave

**Comment by dawoe** [comment]
I fixed the by having the overlay shown on the right side. Available in lastest beta
