### ISSUE TITLE
404 for the create-overlay.html-view

### ISSUE THREAD

**Issue by enkelmedia** [dawoe/umbraco-redirectsviewer#7]
When clicking the "Add redirect"-button in the property editor I get this error:

http://birdie.se.local/~/App_Plugins/RedirectsViewer/views/create-overlay.html 404 (Not Found)

Umbraco: 7.9.2
Redirect Viewer: 1.2

For me chaning this is editor.js

vm.overlay.view = umbRequestHelper.convertVirtualToAbsolutePath("~/App_Plugins/RedirectsViewer/views/create-overlay.html");

to 

vm.overlay.view = umbRequestHelper.convertVirtualToAbsolutePath("/App_Plugins/RedirectsViewer/views/create-overlay.html");

Solved this problem

**Comment by dawoe** [comment]
Hi @enkelmedia 

Could it be related to this : https://umbraco.com/blog/chrome-66-causing-errors-on-some-umbraco-sites/

That was fixed in 7.9.6 : https://our.umbraco.com/download/releases//796

Dave

**Comment by dawoe** [comment]
I think it will be this issue.

Had a similar report on my tour editor package : https://github.com/dawoe/umbraco-tour-editor/issues/17

Dave

**Comment by dawoe** [comment]
I think we talked about this at CG. So i am closing this one
