### ISSUE TITLE
Feature Request: Record those redirects that are used and how often

### ISSUE THREAD

**Issue by PeteDuncanson** [dawoe/umbraco-redirectsviewer#9]
Just thinking out loud here but following on from #8 another method to know if its safe to remove a redirect is if its actually recently be hit. If we could keep a counter of the number of times a redirect has been used then that could be a safe marker that you can delete it.

Obviously we don't want to be hitting the DB for every hit so a in memory score board would be needed that could be flushed to the DB every once in a while and then reset. All we store are the total number of hits to that page per month?

Then you could update the UI to show that number next to each entry and if zero then you can add a "safe to delete" button with an info box ("this redirect hasn't been hit for over a month, so its probably safe to delete."). Something like that.

Not saying this is going to get done but the idea popped in my head and I'd rather share it than lose it :)

**Comment by dawoe** [comment]
Hey @PeteDuncanson 

Thanks for the suggestion. But like I said in #8 i'm using the Umbraco builtin redericts for storing data. And this does not support this.

I also think the chance is slim that they will support it. But maybe it's worth raising these requests on the Umbraco repository

Dave
